/* ==========================================================
   Games grid — reads /games/games.json (generated by
   tools/generate-manifest.js from the games/ folder structure)
   and renders a card per game.
   ========================================================== */
(function () {
  const GRID = () => document.getElementById('game-grid');

  async function fetchManifest() {
    try {
      const res = await fetch('games/games.json', { cache: 'no-store' });
      if (!res.ok) throw new Error('manifest not found');
      return await res.json();
    } catch (e) {
      console.warn('Could not load games/games.json', e);
      return [];
    }
  }

  function cardHtml(game) {
    const thumb = game.thumbnail
      ? `<img src="games/${game.folder}/${game.thumbnail}" alt="${game.name} thumbnail" loading="lazy">`
      : `<span class="game-thumb-fallback">◆</span>`;

    return `
      <article class="game-card">
        <div class="game-thumb">${thumb}</div>
        <div class="game-card-body">
          <h3 class="game-card-title">${escapeHtml(game.name)}</h3>
          <p class="game-card-desc">${escapeHtml(game.description || 'No description available.')}</p>
          <button class="pixel-btn pixel-btn--primary play-btn" data-play="${game.id}">▸ PLAY</button>
        </div>
      </article>`;
  }

  function escapeHtml(str) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
  }

  async function render() {
    const grid = GRID();
    if (!grid) return;
    grid.innerHTML = `<div class="empty-state">loading games…</div>`;

    const games = await fetchManifest();
    if (!games.length) {
      grid.innerHTML = `<div class="empty-state">No games found yet. Drop a folder into <code>/games</code> and run <code>node tools/generate-manifest.js</code>.</div>`;
      return;
    }

    grid.innerHTML = games.map(cardHtml).join('');
    grid.querySelectorAll('[data-play]').forEach(btn => {
      btn.addEventListener('click', () => {
        const game = games.find(g => g.id === btn.dataset.play);
        if (game) window.GGMain.openGame(game);
      });
    });
  }

  window.GGGames = { render };
})();
