/* ==========================================================
   Background music — plays audio files from /music, listed in
   music/music.json (generated by tools/generate-music-manifest.js,
   which picks up any audio file you drop into that folder — mp3,
   ogg, wav, m4a, flac, whatever the browser can play).

   Routed through a small Web Audio graph (source -> gain -> analyser
   -> destination) so js/visualizer.js can read live frequency data
   for the background music visualizer, and so fades/mute/ducking
   are all just gain-node ramps.
   ========================================================== */
(function () {
  const BASE_VOLUME = 0.2;
  const FADE_SEC = 0.7;

  let manifest = [];
  let audioCtx = null;
  let gainNode = null;
  let analyser = null;
  let sourceNode = null;
  let audioEl = null;
  let currentTrack = null;
  let muted = false;
  let duckLevel = 1;      // 1 = full, 0 = ducked (inside a game)
  let started = false;

  function targetVolume() {
    return muted ? 0 : BASE_VOLUME * duckLevel;
  }

  function ensureGraph() {
    if (!audioCtx) {
      audioCtx = new (window.AudioContext || window.webkitAudioContext)();
      gainNode = audioCtx.createGain();
      gainNode.gain.value = 0;
      analyser = audioCtx.createAnalyser();
      analyser.fftSize = 256;
      analyser.smoothingTimeConstant = 0.8;
      gainNode.connect(analyser);
      analyser.connect(audioCtx.destination);
    }
    if (audioCtx.state === 'suspended') audioCtx.resume();
  }

  function fadeTo(vol, seconds) {
    if (!audioCtx || !gainNode) return;
    const now = audioCtx.currentTime;
    gainNode.gain.cancelScheduledValues(now);
    gainNode.gain.setValueAtTime(gainNode.gain.value, now);
    gainNode.gain.linearRampToValueAtTime(Math.max(0, vol), now + seconds);
  }

  async function loadManifest() {
    try {
      const res = await fetch('music/music.json', { cache: 'no-store' });
      if (!res.ok) throw new Error('no manifest');
      manifest = await res.json();
    } catch (e) {
      console.warn('Could not load music/music.json', e);
      manifest = [];
    }
    return manifest;
  }

  function pickTrack() {
    if (!manifest.length) return null;
    return manifest[Math.floor(Math.random() * manifest.length)];
  }

  function play(track) {
    if (!track) return;
    currentTrack = track;
    ensureGraph();
    audioEl = new Audio(`music/${track.file}`);
    audioEl.loop = true;
    audioEl.crossOrigin = 'anonymous';
    sourceNode = audioCtx.createMediaElementSource(audioEl);
    sourceNode.connect(gainNode);
    audioEl.play().catch(() => { /* needs a user gesture; init() is called from one */ });
    fadeTo(targetVolume(), FADE_SEC);
  }

  const api = {
    currentTrackName() { return currentTrack ? currentTrack.name : null; },

    getAnalyser() { return analyser; },

    // Begin playback. Called from a user gesture (the Enter button).
    // `startSilent` forces a silent first run (first-ever visit) without
    // touching the saved mute preference for future visits.
    async init(preferredMuted, startSilent) {
      if (started) return;
      started = true;
      muted = !!preferredMuted;
      if (!manifest.length) await loadManifest();
      const track = pickTrack();
      if (!track) return;
      play(track);
      if (startSilent && gainNode) {
        gainNode.gain.cancelScheduledValues(audioCtx.currentTime);
        gainNode.gain.setValueAtTime(0, audioCtx.currentTime);
      }
    },

    mute() {
      muted = true;
      fadeTo(targetVolume(), FADE_SEC);
    },
    unmute() {
      muted = false;
      if (!started) { this.init(false, false); return; }
      fadeTo(targetVolume(), FADE_SEC);
    },
    isMuted() { return muted; },

    duck() {
      duckLevel = 0;
      fadeTo(targetVolume(), FADE_SEC);
    },
    unduck() {
      duckLevel = 1;
      fadeTo(targetVolume(), FADE_SEC);
    }
  };

  window.GGMusic = api;
})();
