/* ==========================================================
   Background music — plays real audio files from /music,
   using the manifest at music/music.json (generated by
   tools/generate-music-manifest.js). One track is picked at
   random each time the site is opened, kept quiet (0.2), and
   fades in/out around the game player + mute toggle.
   ========================================================== */
(function () {
  const BASE_VOLUME = 0.2;
  const FADE_MS = 700;

  let manifest = [];
  let audioEl = null;
  let currentTrack = null;
  let muted = false;
  let duckLevel = 1;      // 1 = full, 0 = ducked (inside a game)
  let started = false;
  let fadeTimer = null;

  function targetVolume() {
    return muted ? 0 : BASE_VOLUME * duckLevel;
  }

  function fadeTo(vol, ms) {
    if (!audioEl) return;
    clearInterval(fadeTimer);
    const steps = 20;
    const stepTime = ms / steps;
    const start = audioEl.volume;
    const delta = (vol - start) / steps;
    let i = 0;
    fadeTimer = setInterval(() => {
      i++;
      const v = Math.max(0, Math.min(1, start + delta * i));
      audioEl.volume = v;
      if (i >= steps) {
        audioEl.volume = vol;
        clearInterval(fadeTimer);
      }
    }, stepTime);
  }

  async function loadManifest() {
    try {
      const res = await fetch('music/music.json', { cache: 'no-store' });
      if (!res.ok) throw new Error('no manifest');
      manifest = await res.json();
    } catch (e) {
      console.warn('Could not load music/music.json', e);
      manifest = [];
    }
    return manifest;
  }

  function pickTrack() {
    if (!manifest.length) return null;
    return manifest[Math.floor(Math.random() * manifest.length)];
  }

  function play(track) {
    if (!track) return;
    currentTrack = track;
    audioEl = new Audio(`music/${track.file}`);
    audioEl.loop = true;
    audioEl.volume = 0;
    audioEl.play().catch(() => { /* needs a user gesture; init() is called from one */ });
    fadeTo(targetVolume(), FADE_MS);
  }

  const api = {
    currentTrackName() { return currentTrack ? currentTrack.name : null; },

    // Begin playback. Called from a user gesture (the Enter button).
    // `startSilent` forces a silent first run (first-ever visit) without
    // touching the saved mute preference for future visits.
    async init(preferredMuted, startSilent) {
      if (started) return;
      started = true;
      muted = !!preferredMuted;
      if (!manifest.length) await loadManifest();
      const track = pickTrack();
      if (!track) return;
      play(track);
      if (startSilent) {
        // First time ever on the site: stay silent regardless of mute state,
        // without altering the underlying preference.
        if (audioEl) audioEl.volume = 0;
        clearInterval(fadeTimer);
      }
    },

    mute() {
      muted = true;
      fadeTo(targetVolume(), FADE_MS);
    },
    unmute() {
      muted = false;
      if (!started) { this.init(false, false); return; }
      fadeTo(targetVolume(), FADE_MS);
    },
    isMuted() { return muted; },

    duck() {
      duckLevel = 0;
      fadeTo(targetVolume(), FADE_MS);
    },
    unduck() {
      duckLevel = 1;
      fadeTo(targetVolume(), FADE_MS);
    }
  };

  window.GGMusic = api;
})();
